language: swift
os: osx
osx_image: xcode11
script: xcodebuild -project YMKit.xcodeproj -scheme YMKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone XS Max
xcode_scheme: YMKit
xcode_sdk: iphonesimulator13.0
xcode_workspace: YMKit.xcodeproj
