name: Build & Test with Xcode

on: [push, pull_request]

jobs:
  xcode-build:
    runs-on: macos-latest
    strategy:
      matrix:
        sdk: [
          'iphonesimulator13.2',
          'iphonesimulator13.1',
        ]
        include:
          - xcode_app: 'Xcode_11.2.app'
            sdk: 'iphonesimulator13.2'
          - xcode_app: 'Xcode_11.1.app'
            sdk: 'iphonesimulator13.1'
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          sudo xcode-select -switch /Applications/"${xcode_app}"
          xcodebuild \
          -project YMKit.xcodeproj \
          -scheme YMKit \
          -sdk "${sdk}" \
          ONLY_ACTIVE_ARCH=NO \
          | xcpretty && exit ${PIPESTATUS[0]}
        env:
          xcode_app: ${{ matrix.xcode_app }}
          sdk: ${{ matrix.sdk }}

  xcode-test:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: [
          'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.2',
          'platform=iOS Simulator,name=iPhone 11,OS=13.1',
          'platform=iOS Simulator,name=iPhone XS Max,OS=12.4',
          'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.4',
          'platform=iOS Simulator,name=iPhone SE,OS=10.3.1',
        ]
        include:
          - destination: 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.2'
            xcode_app: 'Xcode_11.2.app'
            sdk: 'iphonesimulator13.2'
            simulator_to_install: ''
          - destination: 'platform=iOS Simulator,name=iPhone 11,OS=13.1'
            xcode_app: 'Xcode_11.1.app'
            sdk: 'iphonesimulator13.1'
            simulator_to_install: ''
          - destination: 'platform=iOS Simulator,name=iPhone XS Max,OS=12.4'
            xcode_app: 'Xcode_11.app'
            sdk: 'iphonesimulator13.0'
            simulator_to_install: 'iOS 12.4'
          - destination: 'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.4'
            xcode_app: 'Xcode_11.app'
            sdk: 'iphonesimulator13.0'
            simulator_to_install: 'iOS 11.4'
          - destination: 'platform=iOS Simulator,name=iPhone SE,OS=10.3.1'
            xcode_app: 'Xcode_11.app'
            sdk: 'iphonesimulator13.0'
            simulator_to_install: 'iOS 10.3.1'
    steps:
      - uses: actions/checkout@master
      - name: Install Simulator
        run: |
          if [ "${simulator_to_install}" != "" ]
          then
            sudo xcversion simulators --install="${simulator_to_install}"
          fi
          xcversion simulators
        env:
          simulator_to_install: ${{ matrix.simulator_to_install }}
      - name: Test
        run: |
          sudo xcode-select -switch /Applications/"${xcode_app}"
          xcodebuild clean test \
          -project YMKit.xcodeproj \
          -scheme YMKit \
          -sdk "${sdk}" \
          -destination "${destination}" \
          ONLY_ACTIVE_ARCH=NO \
          | xcpretty && exit ${PIPESTATUS[0]}
        env:
          destination: ${{ matrix.destination }}
          xcode_app: ${{ matrix.xcode_app }}
          sdk: ${{ matrix.sdk }}
