name: Build with Xcode

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
      - uses: actions/checkout@master
      - name: xcodebuild
        run: |
          sudo xcode-select -switch /Applications/Xcode_11.app
          xcodebuild -project YMKit.xcodeproj -scheme YMKit -sdk iphonesimulator13.0 ONLY_ACTIVE_ARCH=NO
