name: Build & Test with Xcode

on: [push]

jobs:
  validate-podspec:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Lint Podspec
        run: pod lib lint YMKit.podspec
  xcode-build:
    runs-on: macos-latest
    strategy:
      matrix:
        sdk: [
          'iphonesimulator13.5',
          'iphonesimulator13.4',
          'iphonesimulator13.2',
          'iphonesimulator13.0',
        ]
        include:
          - sdk: 'iphonesimulator13.5'
            xcode_app: 'Xcode_11.5.app'
          - sdk: 'iphonesimulator13.4'
            xcode_app: 'Xcode_11.4.1.app'
          - sdk: 'iphonesimulator13.2'
            xcode_app: 'Xcode_11.3.1.app'
          - sdk: 'iphonesimulator13.0'
            xcode_app: 'Xcode_11.app'
    steps:
      - uses: actions/checkout@master
      - name: Switch Xcode version
        run: |
          sudo xcode-select -switch /Applications/"${xcode_app}"
          xcodebuild -version
          swift -version
        env:
          xcode_app: ${{ matrix.xcode_app }}
      - name: Generate Xcode project
        run: swift package generate-xcodeproj
      - name: Build Xcode project
        run: |
          xcodebuild \
          -project YMKit.xcodeproj \
          -scheme YMKit-Package \
          -sdk "${sdk}" \
          ONLY_ACTIVE_ARCH=NO \
          | xcpretty && exit ${PIPESTATUS[0]}
        env:
          sdk: ${{ matrix.sdk }}

  xcode-test:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: [
          'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.5',
          'platform=iOS Simulator,name=iPhone SE (2nd generation),OS=13.4',
          'platform=iOS Simulator,name=iPad Air (3rd generation),OS=13.0',
          'platform=iOS Simulator,name=iPhone XS Max,OS=12.4',
          'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.4',
          'platform=iOS Simulator,name=iPhone SE,OS=10.3.1',
        ]
        include:
          - destination: 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.5'
            sdk: 'iphonesimulator13.5'
            simulator_to_install: ''
            xcode_app: 'Xcode_11.5.app'
          - destination: 'platform=iOS Simulator,name=iPhone SE (2nd generation),OS=13.4'
            sdk: 'iphonesimulator13.4'
            simulator_to_install: 'iOS 13.4'
            xcode_app: 'Xcode_11.4.1.app'
          - destination: 'platform=iOS Simulator,name=iPad Air (3rd generation),OS=13.0'
            sdk: 'iphonesimulator13.0'
            simulator_to_install: ''
            xcode_app: 'Xcode_11.app'
          - destination: 'platform=iOS Simulator,name=iPhone XS Max,OS=12.4'
            sdk: 'iphonesimulator13.0'
            simulator_to_install: 'iOS 12.4'
            xcode_app: 'Xcode_11.app'
          - destination: 'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.4'
            sdk: 'iphonesimulator13.0'
            simulator_to_install: 'iOS 11.4'
            xcode_app: 'Xcode_11.app'
          - destination: 'platform=iOS Simulator,name=iPhone SE,OS=10.3.1'
            sdk: 'iphonesimulator13.0'
            simulator_to_install: 'iOS 10.3.1'
            xcode_app: 'Xcode_11.app'
    steps:
      - uses: actions/checkout@master
      - name: Install simulator if needed
        run: |
          if [ "${simulator_to_install}" != "" ]
          then
            sudo xcversion simulators --install="${simulator_to_install}"
          fi
          xcversion simulators
        env:
          simulator_to_install: ${{ matrix.simulator_to_install }}
      - name: Switch Xcode version
        run: |
          sudo xcode-select -switch /Applications/"${xcode_app}"
          xcodebuild -version
          swift -version
        env:
          xcode_app: ${{ matrix.xcode_app }}
      - name: Generate Xcode project
        run: swift package generate-xcodeproj
      - name: Test Xcode project
        run: |
          xcodebuild clean test \
          -project YMKit.xcodeproj \
          -scheme YMKit-Package \
          -sdk "${sdk}" \
          -destination "${destination}" \
          ONLY_ACTIVE_ARCH=NO \
          | xcpretty && exit ${PIPESTATUS[0]}
        env:
          destination: ${{ matrix.destination }}
          sdk: ${{ matrix.sdk }}
