name: Build & Test with Xcode

on: [push]

jobs:
  # validate-podspec:
  #   runs-on: macos-11.0
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Lint Podspec
  #       run: pod lib lint YMKit.podspec
  xcode-test:
    runs-on: macos-11.0
    strategy:
      matrix:
        destination: [
          'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.5',
          'platform=iOS Simulator,name=iPhone 12 mini,OS=14.4',
          'platform=iOS Simulator,name=iPad Air (3rd generation),OS=13.7',
          'platform=iOS Simulator,name=iPhone XS Max,OS=12.4',
          'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.4',
        ]
        include:
          - destination: 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.5'
            sdk: 'iphonesimulator14.5'
            simulator_to_install: ''
            xcode_app: 'Xcode_12.5.app'
          - destination: 'platform=iOS Simulator,name=iPhone 12 mini,OS=14.4'
            sdk: 'iphonesimulator14.4'
            simulator_to_install: ''
            xcode_app: 'Xcode_12.4.app'
          - destination: 'platform=iOS Simulator,name=iPad Air (3rd generation),OS=13.7'
            sdk: 'iphonesimulator14.4'
            simulator_to_install: 'iOS 13.7'
            xcode_app: 'Xcode_12.4.app'
          - destination: 'platform=iOS Simulator,name=iPhone XS Max,OS=12.4'
            sdk: 'iphonesimulator14.5'
            simulator_to_install: 'iOS 12.4'
            xcode_app: 'Xcode_12.5.app'
          - destination: 'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.4'
            sdk: 'iphonesimulator14.5'
            simulator_to_install: 'iOS 11.4'
            xcode_app: 'Xcode_12.5.app'
    steps:
      - uses: actions/checkout@master
      - name: Install simulator if needed
        run: |
          if [ "${simulator_to_install}" != "" ]
          then
            sudo xcversion simulators --install="${simulator_to_install}"
          fi
          xcversion simulators
        env:
          simulator_to_install: ${{ matrix.simulator_to_install }}
      - name: Switch Xcode version
        run: |
          sudo xcode-select -switch /Applications/"${xcode_app}"
          xcodebuild -version
          swift -version
        env:
          xcode_app: ${{ matrix.xcode_app }}
      - name: Generate Xcode project
        run: swift package generate-xcodeproj
      - name: Test Xcode project
        run: |
          xcodebuild clean test \
          -showBuildTimingSummary \
          -project YMKit.xcodeproj \
          -scheme YMKit-Package \
          -sdk "${sdk}" \
          -destination "${destination}" \
          ONLY_ACTIVE_ARCH=NO \
          | xcpretty && exit ${PIPESTATUS[0]}
        env:
          destination: ${{ matrix.destination }}
          sdk: ${{ matrix.sdk }}
