name: Build with Xcode

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - name: xcodebuild
      run: |
        xcodebuild -project YMKit.xcodeproj -scheme YMKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
